Repository Akik4/sfq, pull requests merged in 2025-05, with the labels that each got.

#1 Dishes
  src/main/java/fr/coding/sfq/DishController.java
  src/main/java/fr/coding/sfq/HelloApplication.java
  src/main/java/fr/coding/sfq/HelloController.java
  src/main/java/fr/coding/sfq/HomeController.java
  src/main/java/fr/coding/sfq/MainController.java
  src/main/java/module-info.java
  src/main/resources/fr/coding/sfq/DishView.fxml
  src/main/resources/fr/coding/sfq/HomePage.fxml
  src/main/resources/fr/coding/sfq/hello-view.fxml
  src/main/resources/fr/coding/sfq/mainView.fxml
  src/main/resources/images/placeholder.png
Labels: enhancement

#2 Tables
  src/main/java/fr/coding/sfq/HomeController.java
  src/main/java/fr/coding/sfq/TablesController.java
  src/main/java/fr/coding/sfq/models/Tables.java
  src/main/resources/fr/coding/sfq/HomePage.fxml
  src/main/resources/fr/coding/sfq/TableView.fxml
Labels: enhancement

#6 feat(ORM): adding Hibernate
  pom.xml
  src/main/java/fr/coding/sfq/DishController.java
  src/main/java/fr/coding/sfq/HibernateTest.java
  src/main/java/fr/coding/sfq/models/DishesEntity.java
  src/main/java/fr/coding/sfq/models/EmployeeEntity.java
  src/main/java/fr/coding/sfq/models/OrdersEntity.java
  src/main/java/fr/coding/sfq/models/TablesEntity.java
  src/main/java/fr/coding/sfq/util/HibernateUtil.java
  src/main/java/module-info.java
  src/main/resources/hibernate.cfg.xml
Labels: enhancement

#8 Feature/transaction bdd
  src/main/java/fr/coding/sfq/TimerController.java
  src/main/java/fr/coding/sfq/TransactionsController.java
  src/main/java/fr/coding/sfq/models/TransactionEntity.java
  src/main/java/fr/coding/sfq/util/CountdownTimerUtil.java
  src/main/resources/fr/coding/sfq/Timer.fxml
  src/main/resources/fr/coding/sfq/mainView.fxml
  src/main/resources/hibernate.cfg.xml
Labels: enhancement

#9 Data
  src/main/java/fr/coding/sfq/DishController.java
  src/main/java/fr/coding/sfq/HomeController.java
  src/main/java/fr/coding/sfq/MainController.java
  src/main/java/fr/coding/sfq/TablesController.java
  src/main/resources/fr/coding/sfq/HomePage.fxml
  src/main/resources/fr/coding/sfq/mainView.fxml
Labels: enhancement

#12 fix(dish): clicked based on name and not id
  src/main/java/fr/coding/sfq/DishController.java
Labels: bug

#13 Loading screen
  src/main/java/fr/coding/sfq/DishController.java
Labels: enhancement

#15 Pierre/feature/commande
  src/main/java/fr/coding/sfq/TablesController.java
  src/main/java/fr/coding/sfq/models/OrderDishiesEntity.java
  src/main/java/fr/coding/sfq/models/OrdersEntity.java
  src/main/java/fr/coding/sfq/models/TablesEntity.java
  src/main/resources/hibernate.cfg.xml
Labels: enhancement

#14 Feature/image url
  src/main/java/fr/coding/sfq/DishController.java
  src/main/java/fr/coding/sfq/models/DishesEntity.java
  src/main/resources/fr/coding/sfq/DishView.fxml
Labels: enhancement

#22 Dashboard
  src/main/java/fr/coding/sfq/HelloApplication.java
  src/main/java/fr/coding/sfq/HomeController.java
  src/main/java/fr/coding/sfq/controllers/AllDashboardController.java
  src/main/java/fr/coding/sfq/controllers/DashboardController.java
  src/main/java/fr/coding/sfq/controllers/DishController.java
  src/main/java/fr/coding/sfq/controllers/EmployeeController.java
  src/main/java/fr/coding/sfq/controllers/HomeController.java
  src/main/java/fr/coding/sfq/controllers/MainController.java
  src/main/java/fr/coding/sfq/controllers/OrdersController.java
  src/main/java/fr/coding/sfq/controllers/TablesController.java
  src/main/java/fr/coding/sfq/controllers/TimerController.java
  src/main/java/fr/coding/sfq/controllers/TransactionsController.java
  src/main/java/fr/coding/sfq/models/Dishes.java
  src/main/java/fr/coding/sfq/models/Employee.java
  src/main/java/fr/coding/sfq/models/Orders.java
  src/main/java/fr/coding/sfq/models/Tables.java
  src/main/java/fr/coding/sfq/models/Transaction.java
  src/main/java/module-info.java
  src/main/resources/fr/coding/sfq/AllDashboardView.fxml
  src/main/resources/fr/coding/sfq/DashboardView.fxml
  src/main/resources/fr/coding/sfq/DishView.fxml
  src/main/resources/fr/coding/sfq/EmployeeView.fxml
  src/main/resources/fr/coding/sfq/HomePage.fxml
  src/main/resources/fr/coding/sfq/MainView.fxml
  src/main/resources/fr/coding/sfq/OrdersView.fxml
  src/main/resources/fr/coding/sfq/TableView.fxml
  src/main/resources/fr/coding/sfq/Timer.fxml
  src/main/resources/fr/coding/sfq/TransactionView.fxml
Labels: enhancement

#25 feat(Dashboard) add inProgress and finished orders from the last 24hours
  src/main/java/fr/coding/sfq/controllers/AllDashboardController.java
  src/main/resources/fr/coding/sfq/AllDashboardView.fxml
Labels: enhancement

#28 Feature/chrono order
  src/main/java/fr/coding/sfq/controllers/TablesController.java
  src/main/java/fr/coding/sfq/util/CountdownTimerUtil.java
Labels: enhancement

#27 Dashboard 2
  src/main/java/fr/coding/sfq/controllers/AllDashboardController.java
  src/main/java/fr/coding/sfq/controllers/OrdersController.java
  src/main/java/fr/coding/sfq/controllers/TablesController.java
  src/main/java/fr/coding/sfq/models/OrdersEntity.java
  src/main/java/fr/coding/sfq/util/TransactionsUtil.java
  src/main/resources/fr/coding/sfq/AllDashboardView.fxml
Labels: enhancement

#29 build(maven): fat jar setup
  .gitignore
  dependency-reduced-pom.xml
  pom.xml
  src/main/resources/MANIFEST.MF
Labels: BUILD
